### ISSUE TITLE
能否增加对www.avbase.net的支持

### ISSUE THREAD

**Issue by xiya233** [envyafish/AutoLadyIssue#16]
作者你好，今天通过一个偶然的方式得知此项目，在部署使用后整体感觉非常不错，但可能有点小瑕疵，主要是数据源这块，以下是我的一点小建议。

能否考虑增加对AVbase这个站点的支持？AVbase的数据比Javbus和JavLibrary的数据全，并且AVbase更新也快，基本可以保持和片商在同一天内更新。

另外AVbase对一些小片商的片有更准确的AV女优个人信息，比如SIRO、200GANA、300MIUM这种，片商一般都用假的AV女优姓名，但是AVbase可以分辨出真实的AV女优姓名。

**Comment by xiya233** [comment]
还有我不知道作者是否把这个项目定位为专注于PT使用，如果不是的话，是否可以考虑增加sukebei.nyaa.si，这个网站更新BT种子的速度比PT站快的多，很多新片的BT种子都能第一时间在这个站点找到。

**Comment by silence9527** [comment]
现在还不能搜索fc

**Comment by envyafish** [comment]
计划中。。。

**Comment by envyafish** [comment]
1.2.1已切换到avbase源，感谢提供信息
