### ISSUE TITLE
vx一次输入查找多个番号

### ISSUE THREAD

**Issue by su1xiao** [envyafish/AutoLadyIssue#19]
请问作者，当前阶段一次性只能输入并搜索一个番号吧？
因为资源来源问题，我会收到一串番号，想问下作者后续是否有更新：一次性输入并查找多个番号的打算？

**Comment by envyafish** [comment]
可以

**Comment by silence9527** [comment]
好你个小黄人，别人来一个，你来一串是吧

**Comment by su1xiao** [comment]
感谢作者

**Comment by envyafish** [comment]
1.2.4已支持，可以用空格 换行 | 逗号 进行番号区分
![b39bf3ab844beafa8f9754d5f390cc4](https://github.com/user-attachments/assets/72f1224e-47f3-4085-be41-e2e741bccaac)
