### ISSUE TITLE
未经AL下载的已入库资源会重复下载

### ISSUE THREAD

**Issue by ZACKLZ** [envyafish/AutoLadyIssue#2]
现象：例如通过手动或xx插件订阅下载的新番，在AL上显示[已入库]，但AL还是会再次进行下载
目标：跳过已入库资源，避免重复下载

**Comment by envyafish** [comment]
> 现象：例如通过手动或xx插件订阅下载的新番，在AL上显示[已入库]，但AL还是会再次进行下载 目标：跳过已入库资源，避免重复下载

AL不会下载未订阅的影片，榜单订阅也不会订阅已入库的影片，你这个问题我不理解

**Comment by ZACKLZ** [comment]
订阅中，但媒体库已经入库了，会重新下载
是不是可以加个已入库状态，入库的直接取消订阅呗

**Comment by envyafish** [comment]
> 订阅中，但媒体库已经入库了，会重新下载 是不是可以加个已入库状态，入库的直接取消订阅呗

涉及到洗版的功能，不好判断用户意图

**Comment by ZACKLZ** [comment]
> > 订阅中，但媒体库已经入库了，会重新下载 是不是可以加个已入库状态，入库的直接取消订阅呗
> 
> 涉及到洗版的功能，不好判断用户意图

配置里可以增设洗板开关，关闭状态只要入库就放弃下载，开启状态可以配置成中文字幕洗板/破解无码洗板/UHD资源洗板
