### ISSUE TITLE
报错，好像是mt连不上？

### ISSUE THREAD

**Issue by su1xiao** [envyafish/AutoLadyIssue#20]
�2024-11-09 07:26:10 INFO - /usr/local/lib/python3.12/threading.py:1032 - 过滤完成，得到####的种子资源：Torrent({'id': #####, 'site': 'mt', 'code': '###', 'size_mb': 6269.6919775009155, 'seeders': 359, 'title': '##### #######', 'chinese': True, 'uc': False, 'uhd': False, 'download_url': ''}),即将开始下载种子文件
)Exception in thread Thread-32 (lambda1):
#Traceback (most recent call last):
P  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
C  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
.    self._target(*self._args, **self._kwargs)
T  File "api/services/imessage.py", line 71, in api.services.imessage.do_sub.lambda1
=  File "services/__init__.py", line 124, in services.run_sub
=  File "services/__init__.py", line 135, in services.run_sub
X  File "modules/ptsite/mteam.py", line 105, in modules.ptsite.mteam.MTeam.download_seed
1TypeError: 'Torrent' object is not subscriptable

**Comment by envyafish** [comment]
已修复
