### ISSUE TITLE
订阅点执行下载没有反应

### ISSUE THREAD

**Issue by qiniuweihe** [envyafish/AutoLadyIssue#6]
<img width="722" alt="image" src="https://github.com/user-attachments/assets/151943d0-b277-48a6-b5d5-2336e98b10de">
日志显示 ok ，但是下载器中没有下载任务，也没有什么报错

**Comment by envyafish** [comment]
> <img alt="image" width="722" src="https://private-user-images.githubusercontent.com/40459148/373685340-151943d0-b277-48a6-b5d5-2336e98b10de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNzAxNzYsIm5iZiI6MTcyODI2OTg3NiwicGF0aCI6Ii80MDQ1OTE0OC8zNzM2ODUzNDAtMTUxOTQzZDAtYjI3Ny00OGE2LWI1ZDUtMjMzNmU5OGIxMGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAyNTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlM2ZjM2IzNWVmMGFkYzZhMWViM2VmYmM4NGJlNzNlMjZiZjUzZGE2YzkwYTYzYzNmMGU2OGMxM2NiZTllMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4wwScDBsuH4S960b-bwO9FmAcJV8hKbfuSHQUhr9g0Q"> 日志显示 ok ，但是下载器中没有下载任务，也没有什么报错

版本号

**Comment by UniqueXXL** [comment]
我也一样 qb v4.6.5

**Comment by alaya233** [comment]
同样，qb 4.6.5，docker版

**Comment by envyafish** [comment]
AL版本号

**Comment by envyafish** [comment]
已修复
