### ISSUE TITLE
搜索正常，但是首页资源加载失败，有科学网络

### ISSUE THREAD

**Issue by skycc11** [envyafish/AutoLadyIssue#8]
![image](https://github.com/user-attachments/assets/c014d0e2-8969-4a95-9f20-10ea4711b143)
版本号为1.1.3最新版本
测试过老版本也有同样的问题

留学节点试过日本|美国|香港均无法加载，相关数据库网站可以正常访问

**Comment by Yangrixiao** [comment]
我这javdb和javbus 能用，javlib有盾。javdb不能日本节点，javbus好像不能用美国节点

**Comment by tony3080** [comment]
> 我这javdb和javbus 能用，javlib有盾。javdb不能日本节点，javbus好像不能用美国节点

你好。请问一下javdb和javbus的cookie是怎么抓的，我F12抓的，都连不上，是需要什么工具吗？

**Comment by Yangrixiao** [comment]
> > 我这javdb和javbus 能用，javlib有盾。javdb不能日本节点，javbus好像不能用美国节点
> 
> 你好。请问一下javdb和javbus的cookie是怎么抓的，我F12抓的，都连不上，是需要什么工具吗？

我直接 浏览器复制的

**Comment by tony3080** [comment]
> > > 我这javdb和javbus 能用，javlib有盾。javdb不能日本节点，javbus好像不能用美国节点
> > 
> > 
> > 你好。请问一下javdb和javbus的cookie是怎么抓的，我F12抓的，都连不上，是需要什么工具吗？
> 
> 我直接 浏览器复制的

![photo_2024-10-10_12-20-01](https://github.com/user-attachments/assets/8ad8f04d-6df7-450c-91d8-b70a12a61f5e)
是这里直接复制cookie的全部吗？我是这样复制的，但是还是连不上。

**Comment by Yangrixiao** [comment]
> > > > 我这javdb和javbus 能用，javlib有盾。javdb不能日本节点，javbus好像不能用美国节点
> > > 
> > > 
> > > 你好。请问一下javdb和javbus的cookie是怎么抓的，我F12抓的，都连不上，是需要什么工具吗？
> > 
> > 
> > 我直接 浏览器复制的
> 
> ![photo_2024-10-10_12-20-01](https://private-user-images.githubusercontent.com/127909395/375215871-8ad8f04d-6df7-450c-91d8-b70a12a61f5e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzQ0MzAsIm5iZiI6MTcyODUzNDEzMCwicGF0aCI6Ii8xMjc5MDkzOTUvMzc1MjE1ODcxLThhZDhmMDRkLTZkZjctNDUwYy05MWQ4LWI3MGExMmE2MWY1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNDIyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmM5MDI2ZGY3MjZjMWVkZGNjNmI1OWQ3MDA2ZGRlOTAwOTkwYjQ1MjM1YmRiNWRiMzNkZWY4ZGE1ZTZiNzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IkXfzLqYQ8Ux-p9Uq0-vlcf_Puh9pie3NMkhEBQ079w) 是这里直接复制cookie的全部吗？我是这样复制的，但是还是连不上。

我也是这样抓的 我是登录了账号不知道是不是这个原因

**Comment by tony3080** [comment]
> > > > > 我这javdb和javbus 能用，javlib有盾。javdb不能日本节点，javbus好像不能用美国节点
> > > > 
> > > > 
> > > > 你好。请问一下javdb和javbus的cookie是怎么抓的，我F12抓的，都连不上，是需要什么工具吗？
> > > 
> > > 
> > > 我直接 浏览器复制的
> > 
> > 
> > ![photo_2024-10-10_12-20-01](https://private-user-images.githubusercontent.com/127909395/375215871-8ad8f04d-6df7-450c-91d8-b70a12a61f5e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzQ0MzAsIm5iZiI6MTcyODUzNDEzMCwicGF0aCI6Ii8xMjc5MDkzOTUvMzc1MjE1ODcxLThhZDhmMDRkLTZkZjctNDUwYy05MWQ4LWI3MGExMmE2MWY1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNDIyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmM5MDI2ZGY3MjZjMWVkZGNjNmI1OWQ3MDA2ZGRlOTAwOTkwYjQ1MjM1YmRiNWRiMzNkZWY4ZGE1ZTZiNzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IkXfzLqYQ8Ux-p9Uq0-vlcf_Puh9pie3NMkhEBQ079w) 是这里直接复制cookie的全部吗？我是这样复制的，但是还是连不上。
> 
> 我也是这样抓的 我是登录了账号不知道是不是这个原因

我也是登录了帐号的，就是首页的热门出不来。

**Comment by skycc11** [comment]
> 我这javdb和javbus 能用，javlib有盾。javdb不能日本节点，javbus好像不能用美国节点

感谢，换了个新加坡节点确实能加载出首页了
