### ISSUE TITLE
Jellyfin连接测试出错：400

### ISSUE THREAD

**Issue by BugGeeker** [envyafish/AutoLadyIssue#9]
Jellyfin内网地址：http://192.168.1.100:9096
用户名和秘钥也配置无误，docker日志显示Jellyfin连接测试出错：400
<img width="511" alt="image" src="https://github.com/user-attachments/assets/d14cc04a-318d-4031-adc1-38a4a5b09654">
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/96fa9b16-0a30-4623-85ad-7e44d33b5300">
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/d8e52613-3fef-4d2c-90ae-e75a90fc7bb7">

**Comment by silence9527** [comment]
哈哈哈哈啊哈哈，俺也一样，很久了

**Comment by a-Stranger12138** [comment]
同样的问题，换emby可以连上

**Comment by envyafish** [comment]
版本1.4.2，已修复
